version: "1.0"

services:
  db:
    restart: always
    container_name: database
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/data-import:/data-import
      - ./database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - ${PGPORT}:${PGPORT}

volumes:
  pgdata:
